name: Deploy to Azure App Service

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: onboarding-55f7be69    # Ändra till ditt Azure App Service namn
  AZURE_WEBAPP_PACKAGE_PATH: '.'            # path to your web app project
  NODE_VERSION: '22.x'                      # Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Install dependencies'
      run: |
        npm ci
        npm install --include=dev

    - name: 'Generate Prisma Client'
      run: |
        npx prisma generate

    - name: 'Build application'
      run: |
        npm run build

    - name: 'Handle Database Schema'
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Attempting to run migrations..."

        # Try to run migrations normally first
        if npx prisma migrate deploy; then
          echo "✅ Migrations completed successfully!"
        elif npx prisma migrate status 2>&1 | grep -q "P3005\|not empty"; then
          echo "⚠️  Database has existing schema. Creating baseline..."

          # Mark existing migrations as applied (baseline)
          echo "Marking existing migrations as applied..."
          npx prisma migrate resolve --applied 20250527114024_initial || true
          npx prisma migrate resolve --applied 20250527125728_add_task_link || true

          # Now try to deploy the new migration
          echo "Deploying new buddy preparation migration..."
          npx prisma migrate deploy

          echo "✅ Database schema updated successfully!"
        else
          echo "❌ Migration failed with unexpected error"
          exit 1
        fi

    - name: 'Create deployment package'
      run: |
        # Remove dev dependencies for production
        npm prune --production
        # But keep prisma for runtime
        npm install prisma @prisma/client
        # Ensure Prisma client is generated for production
        npx prisma generate

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: 'Post-deployment: Verify Prisma'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          # Optional: verify that the app is running and database is accessible
          echo "Deployment completed successfully"