name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to migrate'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'

    - name: 'Install dependencies'
      run: |
        npm ci
        npm install prisma @prisma/client

    - name: 'Generate Prisma Client'
      run: |
        npx prisma generate

    - name: 'Run Database Migration'
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        echo "Running migration for ${{ github.event.inputs.environment }} environment"

        # Try to run migrations normally first
        if npx prisma migrate deploy; then
          echo "✅ Migrations completed successfully!"
        elif npx prisma migrate status 2>&1 | grep -q "P3005\|not empty"; then
          echo "⚠️  Database has existing schema. Using db push for safety..."
          npx prisma db push --accept-data-loss
          echo "✅ Schema synchronized successfully!"
        else
          echo "❌ Migration failed with unexpected error"
          exit 1
        fi

    - name: 'Verify Migration'
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        npx prisma migrate status