name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "onboarding-app"
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: npm install
        run: npm install

      - name: Force regenerate Prisma client with correct binaries
        run: |
          echo "=== Cleaning existing Prisma client ==="
          rm -rf node_modules/.prisma
          rm -rf node_modules/@prisma/client/runtime
          echo "=== Generating Prisma client with Linux binaries ==="
          npx prisma generate --no-engine
          npx prisma generate

      - name: Debug - Verify Prisma binaries
        run: |
          echo "=== Checking generated Prisma files ==="
          ls -la node_modules/.prisma/client/ || echo "No .prisma/client found"
          echo "=== Looking for Linux query engine binary ==="
          find node_modules -name "*query*engine*debian*" -type f || echo "No Linux query engine found"
          find node_modules -name "libquery_engine*" -type f || echo "No libquery_engine found"

      - name: Run database migrations
        run: |
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Seed database (optional)
        run: |
          npx prisma db seed || echo "No seed script found, skipping..."
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Build application
        run: |
          npm run build

      - name: Prepare standalone deployment
        run: |
          echo "=== Copying static files ==="
          cp -r ./public ./.next/standalone/ || true
          cp -r ./.next/static ./.next/standalone/.next/ || true
          echo "=== Copying Prisma client to standalone build ==="
          mkdir -p ./.next/standalone/node_modules/.prisma
          mkdir -p ./.next/standalone/node_modules/@prisma
          cp -r ./node_modules/.prisma/client ./.next/standalone/node_modules/.prisma/
          cp -r ./node_modules/@prisma/client ./.next/standalone/node_modules/@prisma/
          echo "=== Copying prisma folder ==="
          cp -r ./prisma ./.next/standalone/
          echo "=== Verifying Linux binaries in standalone build ==="
          find ./.next/standalone/node_modules -name "*query*engine*debian*" -type f || echo "No Linux query engine in standalone"

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./.next/standalone