name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "onboarding-app"
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: npm install
        run: npm install

      - name: Generate Prisma client with Linux binaries
        run: |
          echo "=== Generating Prisma client ==="
          npx prisma generate

      - name: Verify Prisma client generation
        run: |
          echo "=== Verifying Prisma client files ==="
          ls -la node_modules/.prisma/client/ || echo "No .prisma/client found"
          ls -la node_modules/@prisma/client/runtime/ || echo "No runtime found"
          echo "=== Checking for Linux binaries ==="
          find node_modules -name "*query*engine*debian*" -type f | head -5 || echo "No Linux query engine found"

      - name: Run database migrations
        run: |
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Seed database (optional)
        run: |
          npx prisma db seed || echo "No seed script found, skipping..."
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Build application
        run: |
          npm run build

      - name: Prepare standalone deployment
        run: |
          echo "=== Copying static files ==="
          cp -r ./public ./.next/standalone/ || true
          cp -r ./.next/static ./.next/standalone/.next/ || true
          echo "=== Copying Prisma client ==="
          mkdir -p ./.next/standalone/node_modules/.prisma
          mkdir -p ./.next/standalone/node_modules/@prisma
          cp -r ./node_modules/.prisma/client ./.next/standalone/node_modules/.prisma/ || echo "Failed to copy .prisma/client"
          cp -r ./node_modules/@prisma/client ./.next/standalone/node_modules/@prisma/ || echo "Failed to copy @prisma/client"
          echo "=== Copying prisma schema ==="
          cp -r ./prisma ./.next/standalone/ || echo "Failed to copy prisma folder"
          echo "=== Final verification ==="
          ls -la ./.next/standalone/node_modules/@prisma/client/runtime/ || echo "No runtime in standalone"

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./.next/standalone